name: Static analysis - app

on:
  push:
    branches:
      - "**"
    paths:
      - "app/**"
      - ".github/workflows/app*"

jobs:
  static-analysis:
    uses: ./.github/workflows/reusable-static-analysis.yaml
    with:
      workdir: app
