name: Static analysis - core

on:
  push:
    branches:
      - "**"
    paths:
      - "core/**"
      - ".github/workflows/core*"

jobs:
  static-analysis:
    uses: ./.github/workflows/reusable-static-analysis.yaml
    with:
      workdir: core
