name: Static analysis (reusable)

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check formatting
        run: poetry run task lint
      - name: Check linter
        run: poetry run task check-format
      - name: Check typing
        run: poetry run task typing
      - name: Test with pytest
        run: poetry run task test
